### ISSUE TITLE
Get a MissingReferenceException when trying to Reset the turn

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#41] opened 2016-11-30 23:16 UTC
it takes me to this place in the code... and does not reset the first player's Actions. But I can still take one action and it goes to the next person. I can go on and play everyone else but get this error every time I get back to the first player. 

The code the error takes me to:
![referencemissing](https://cloud.githubusercontent.com/assets/8864798/20775417/024be33a-b718-11e6-967a-b993b10cd2a7.PNG)

These are the actions from last round that are stuck in there:
![playeractions](https://cloud.githubusercontent.com/assets/8864798/20775427/1cfde0ac-b718-11e6-8ec2-156835ad3297.PNG)

**Comment by gbohnen** [comment] 2016-12-06 20:09
I believe this is an error caused by an empty situation method. It should be fixed once situations are fully implemented.

**Comment by gbohnen** [comment] 2016-12-06 20:09
This error usually occurs when an object has been destroyed. This probably happened because of a situation that was auto-resolved. Needs more testing to be sure

**Closed as completed** 2016-12-12 00:08 UTC
Labels: Bug
